calbl: 800
calwh: 1200
dlbd: 300
dob: 20170330
ibmc: 0
iboth: 1
icalbl: 800
icalct: 0
icalib: 1
icalplot: 0
icalwh: 1200
icmd: 0
idc: 1
ideg3: 0
ideg4: 0
ides: 0
iedge: 0
igeo1: 1
igeo2: 1
igeo3: 1
igeo4: 1
igeom: 1
igrayq: 0
iipro: 0
iliss: 60
inclin: 1
invern: 0
iobs: 1
iobsD1: 0
iobsD2: 1
iobsDbl: 800
iobsDwh: 1200
iobsbl: 200
iobswh: 1800
iquick: 0
is: 1536
itest: 1
ivchan: 14000
ivprof1: 1
ivprof2: 1
ivprof3: 1
ixy: 1
ja1: 151
ja3: 851
jaddprof: 0
jjpro: 0
jliss: 0
jparab: 10
js: 1024
jtest: 121
jxpro1: 0
jxpro2: 0
jxpro3: 0
jypas: 45000
kedgx: 0
kedgy: 0
labsem: 0
laddx: 0
laddy: 0
lbda: 6563
lbdvel1: 20
lbdvel2: 35
lbdvel3: 50
leastsq: 1
li: 442000
lj: 61000
marge: 0
margline: 0
meanpro: 1
mgx: 12
mgy: 12
milsec: 500
mupris: 9000
mustep: 2500
nbcln: 1024
nblgn: 1536
ncam1: 1
ncurv1: 5
ncurv2: 6
nfb1: 1
nfb2: 1
nfplot: 1
nfx1: 1
nfx2: 5
nfy1: 1
nfy2: 25
nline: 1
nm: 9
nob1: 1
nob2: 1
nobstep: 5
nr: 5
ntest: 9
ntmax: 5
ntrans: 5
nwinp: 1
priscan: 4
tdc1: 0
tdc2: 24000000
tff1: 0
tff2: 24000000
tfs1: 0
tfs2: 24000000
tob1: 0
tob2: 24000000
x1cal: 100
x2cal: 750
y1cal: 200
y2cal: 700
